spring.application.name=chefsphere-ums
#DB config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
server.address=0.0.0.0
server.port=8080
#JWT expiration time in msec for 5 hours
jwt.expiration.time=18000000
# JWT secret
jwt.secret=617b7c292a0698a897e6ff73324285be2ca049857c8802e26a4cce2214d899c4
#for imagekit token
imagekit.public-key=public_iPeORsPiP4+DYw+TDTsCHwg9sXs=
imagekit.private-key=private_5Z2pcMnB51DQKwyFEaAy9znhcOo=
imagekit.url-endpoint=https://ik.imagekit.io/xlpbkk1xx/chefsphere
#frontend-url
frontend.url=${FRONTEND_URL}